# SPDX-FileCopyrightText: (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

---
apiVersion: v1
kind: Service
metadata:
  name: ntpserv
spec:
  selector:
    app: {{ .Release.Name }}-ntpserv
  ports:
    - protocol: UDP
      port: 123
      targetPort: 123
