# SPDX-FileCopyrightText: (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Release.Name }}-broker-cert
spec:
  secretName: {{ .Release.Name }}-broker-tls
  issuerRef:
    name: {{ .Release.Name }}-ca-issuer
    kind: Issuer
  commonName: "broker.scenescape.intel.com"
  dnsNames:
  - "broker.scenescape.intel.com"
  - "broker"
  - "broker.{{ .Release.Namespace }}"
  - "broker.{{ .Release.Namespace }}.svc.cluster.local"
  duration: 8760h
  renewBefore: 720h
