# SPDX-FileCopyrightText: (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

---
apiVersion: v1
kind: Service
metadata:
  name: broker
  annotations: {{- toYaml .Values.mqttService.annotations | nindent 4 }}
spec:
  selector:
    app: {{ .Release.Name }}-broker
  ports:
  - name: "1883"
    protocol: TCP
    port: 1883
    targetPort: 1883
  - name: "1884"
    protocol: TCP
    port: 1884
    targetPort: 1884
{{- if .Values.mqttService.nodePort.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: broker-np
  annotations: {{- toYaml .Values.mqttService.nodePort.annotations | nindent 4 }}
spec:
  type: NodePort
  selector:
    app: {{ .Release.Name }}-broker
  ports:
  - name: "1883"
    protocol: TCP
    port: 1883
    targetPort: 1883
    nodePort: {{ .Values.mqttService.nodePort.nodePort }}
{{- end }}
{{- if .Values.mqttService.loadBalancer.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: broker-lb
  annotations: {{- toYaml .Values.mqttService.loadBalancer.annotations | nindent 4 }}
spec:
  type: LoadBalancer
  selector:
    app: {{ .Release.Name }}-broker
  ports:
  - name: "1883"
    protocol: TCP
    port: 1883
    targetPort: 1883
  externalTrafficPolicy: {{ .Values.mqttService.loadBalancer.externalTrafficPolicy }}
  {{- if (default .Values.mqttService.loadBalancer.loadBalancerIP false) }}
  loadBalancerIP: {{ .Values.mqttService.loadBalancer.loadBalancerIP }}
  {{- end }}
{{- end }}
